### ISSUE TITLE
ContentAlign and AlignItems combination cause wrong behaviour

### ISSUE THREAD

**Issue by jalopez1986** [facebook/yoga#1008]
# Report

- [ X] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Configure a Flexbox in this way

```javascript
     <View style={{width: 300, height: 300, backgroundColor: 'red', flexDirection: 'row',flexWrap:'wrap', alignContent:'space-around',alignItems:'flex-end' }}>
        <View style={{width: 150, height: 50, backgroundColor: 'powderblue'}} />
        <View style={{width: 120, height: 100, backgroundColor: 'skyblue'}} />
        <View style={{width: 120, height: 50, backgroundColor: 'steelblue'}} />
      </View>
  
```

# Expected Behavior
The elements must be show like this: (This is the web representation)
![image](https://user-images.githubusercontent.com/6043040/83539793-1ec19a00-a4bd-11ea-967f-16df6cc79d34.png)

# Actual Behavior
![image](https://user-images.githubusercontent.com/6043040/83539739-0b163380-a4bd-11ea-8681-bca949a299cb.png)
the elements are wrong located, the combination of contentAlign and AlignItem causes strange behaviours.
Whit combination like
ContentAlign: space-around or space-between with
AlignItems: center or flex-end 
The algorithm locate the elements in awrong way.

# Link to Code
https://stackblitz.com/edit/typescript-yoga-rg4mcr?file=index.ts

**Comment by woehrl01** [comment]
Hi @jalopez1986

Thanks for reporting this. I just pushed a PR for the fix.

**Comment by jalopez1986** [comment]
You're Welcome, this is an excellent library.
Thanks to you for solve it
@woehrl01  Do you know approximately how often a new version is released with bug fixes?

**Comment by woehrl01** [comment]
Unfortunately I can't give you an ETA for a new published version, as I haven't been involved in that project for a long time. The maintainer of Facebook has changed since the last time.

The last fixes involved the following steps: it need to undergo an external review (on github), then it gets imported to the internal repository, then an internal review (facebook) takes place. After that at best, no internal tests are failing (which rely on the previous behavior). If nothing fails there should be no real blocker in creating a new release to my knowledge.

Maybe @SidharthGuglani, you can give more insight into the current process?
