### ISSUE TITLE
https://yogalayout.com/ can not load In mainland China

### ISSUE THREAD

**Issue by zongxiaomi** [facebook/yoga#1143]
# Report

# Expected Behavior
normal load

# Actual Behavior
 load error

**Comment by NickGerleman** [comment]
The webpage is backed by GitHub Pages (see https://github.com/facebook/yoga/commits/gh-pages for recent deploys). So we are reliant on their infrastructure to an extent.

If this issue was not transient, could you reopen it with details on how the connection fails? E.g. is there a 404, a DNS issue (that might be under our control)? Etc?
