### ISSUE TITLE
javascript package taking too much memory

### ISSUE THREAD

**Issue by joe06102** [facebook/yoga#1157]
# Report

- [checked] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
When using yoga-layout & create 3 simple nodes in jsc(ios) & quickjs(android)，it calculates the layout as expected, but taking almost **100 MB** memory on the mobile, but on the browser, the heap only takes about **3~4 MB**.

I decide to re-bind the js with embind & re-compile the yoga, now it takes about **10 ~ 30 MB** on both the mobile & pc platforms, but I think the memory is still unacceptable.

I'm a c/cpp rookie and wondering is there any way to lower the memory consume. I would appreciate if anyone can help me with it.

# Link to Code

[compiled yoga.js with embind & emcc](https://gist.github.com/joe06102/bf7d3e906d37028ba3a4dc74b9ebaf1f.js)

```shell
# build flags with emcc
emcc -lembind -o0 -g sources/yoga/Utils.cpp sources/yoga/YGConfig.cpp sources/yoga/YGEnums.cpp sources/yoga/YGLayout.cpp sources/yoga/YGNode.cpp sources/yoga/YGNodePrint.cpp sources/yoga/YGStyle.cpp sources/yoga/YGValue.cpp sources/yoga/Yoga.cpp sources/yoga/log.cpp sources/yoga/event/event.cpp sources/yoga/internal/experiments.cpp sources/Config.cc sources/Node.cc -lembind -o3 -o demo/yoga.js -sWASM=0 -sFILESYSTEM=0 -sWASM_ASYNC_COMPILATION=0 -sEXIT_RUNTIME=1 -sINITIAL_MEMORY=3145728 -sTOTAL_STACK=1048576 -sALLOW_MEMORY_GROWTH=1 -sMAXIMUM_MEMORY=10485760 -sMEMORY_GROWTH_GEOMETRIC_CAP=10485760 -sJS_MATH=1 -sPOLYFILL=0 -sLEGACY_RUNTIME=0 -sENVIRONMENT=web,webview,node -sINCOMING_MODULE_JS_API=[] -sEXPORTED_RUNTIME_METHODS=ccall,cwrap -o demo/yoga.js -sWASM=0 -sEXPORTED_RUNTIME_METHODS=ccall,cwrap
```

**Comment by NickGerleman** [comment]
QuickJS and JSC on iOS (outside the browser) are a bit unique compared to JS engines used by browsers, since neither use a JIT. 

For environments outside the browser, I suspect you could get better performance characteristics using the FFI between the JS engine, and a regularly compiled (not asm.js) copy of Yoga. I think this is how the Node bindings work right now.

**Comment by NickGerleman** [comment]
1813748eaa60e6129c1e1c00c08322b5687b1702 adds some new bindings here, where there was some care taken to look at the optimization flags. I think you might end up getting better results using them (it is I think close to the best we can do with asm.js/WebAssembly). Keep in mind the nodes must manually be freed, or will otherwise leak.

**Comment by joe06102** [comment]
Thx! We've turned to the css-layout and it works fine(speed & memory are ok); I will try the latest binding later.
