### ISSUE TITLE
Move YGConfig behavior flags from methods to enums

### ISSUE THREAD

**Issue by NickGerleman** [facebook/yoga#1211]
YGConfig has a legacy APIs `UseLegacyStretchBehaviour()`, and a conformance API `UseWebDefaults()`. Adding a `UseXXX()` method for each legacy flag we may add could pollute the API, and needs a new binding for each.

Instead, we should aim to:
1. Add `UseLegacyBehavior()` accepting an enum
    1. (Checked with a couple UK team members that US English is preferred in API names)
2. Change `UseLegacyStretchBehaviour` to `YGBehaviorStretchFlexBasis`. 
3. Make UseWebDefaults the default
    1. Add a `YGBehaviorLegacyDefaults`

**Comment by nicoburns** [comment]
1. Can I add to this: document the new APIs. I believe there is currently no public documentation on the existing config flags.
2. Is the idea that you'd call `UseLegacyBehavior()` multiple times with different variants to turn on different legacy flags? It might be a good idea to have an API to turn the flag off again for completeness.

**Comment by NickGerleman** [comment]
I'm looking at a slightly different API now, where we unify YGExperimentalFeature, and flags like UseLegacyStretchBehaviour(), under a new generalized YGEratta API.

By default Yoga users would get all conformance fixes, but they could control the specific ones via YGEratta flag bitset, and we would have convenience options to opt into "classic" behavior, or to opt out of all eratta at once (e.g. for old projects not being touched anywhere).

Not sure whether `UseWebDefaults` should go through the same or different mechanism. But a breaking change would be a good time to make that the default behavior as well.

**Comment by nicoburns** [comment]
@NickGerleman I agree that making all the breaking changes at once is a good idea. However, I keep coming back to the fact that even Yoga's existing "web compatible" mode almost certainly isn't that spec compliant. Which would imply further breaking changes down the line for users of that mode. The more I think about it, the more I think it might be better to:

1. Adapt Yoga's existing flexbox implementation so that it can interoperate with other layout algorithms (in such a way that does not affect the computed layout in any way), and ideally such that it accepts style data and output layout data via an interface rather than being coupled to Yoga's node tree implementation.
2. Freeze that layout algorithm entirely (quirks and all)
3. Drop in an existing spec-compliant layout implementation (e.g. one from Taffy or FlexLayout - this could be copy-pasted into Yoga if required for code ownership reasons), and allow users to switch between the two mechanisms using the `display` style (e.g. we can `display: flex` and `display: legacy-flex`). A Grid implementation could be also be added using the same algorithm-switching mechanism.

Potentially you could just do 1 and 2, and allow embedders of Yoga (e.g. React Native) to implement 3 themselves. See https://github.com/react-native-community/discussions-and-proposals/pull/540/files#r1127103751 for how that might then be exposed in a high-level API.

Effectively my proposal is to freeze the current version of the algorithm as it's own "legacy flexbox" algorithm within Yoga (while adding new algorithm which use entirely separate code paths at a high level) rather than freezing conservative consumers of Yoga on an old Yoga version or carefully, carefully trying not to break them with piecemeal incremental API evolution (I can almost guarantee we will break them anyway, however careful we are).

**Comment by NickGerleman** [comment]
This was done with the YGErrata API.
