### ISSUE TITLE
What to do next after YogaKit is deprecated

### ISSUE THREAD

**Issue by jiasongs** [facebook/yoga#1309]
i noticed that YogaKit is deprecated, what should I do for the project.
also, the minimum supported version has been changed to 13.4, why is it not 13.0

**Comment by NickGerleman** [comment]
> i noticed that YogaKit is deprecated, what should I do for the project.

If you need to continue relying on YogaKit I would recommend inlining the source into the current project you are using. YogaKit has not received a new release in a number of years, so there likely should not be major changes here. It does crystalize that we are not going to be providing updates to it in the future beyond the Yoga 2.0 release we plan for this month. E.g. if a XCode update breaks compatibility, we may not push out an update.

> the minimum supported version has been changed to 13.4, why is it not 13.0

I bumped the minimum version to 13.4 as a hygiene measure to match the minimum supported version of iOS that Meta ships against, both for internal projects, and for OSS projects like React Native. In general I would like to minimize the delta of configurations we ship which do not receive real-world usage, since we don't have that real-world validation that everything works as expected. Practically, there have not been code changes, so changing it locally to something lower would almost definitely work.

**Comment by jiasongs** [comment]
> React Native



> > i noticed that YogaKit is deprecated, what should I do for the project.
> 
> If you need to continue relying on YogaKit I would recommend inlining the source into the current project you are using. YogaKit has not received a new release in a number of years, so there likely should not be major changes here. It does crystalize that we are not going to be providing updates to it in the future beyond the Yoga 2.0 release we plan for this month. E.g. if a XCode update breaks compatibility, we may not push out an update.
> 
> > the minimum supported version has been changed to 13.4, why is it not 13.0
> 
> I bumped the minimum version to 13.4 as a hygiene measure to match the minimum supported version of iOS that Meta ships against, both for internal projects, and for OSS projects like React Native. In general I would like to minimize the delta of configurations we ship which do not receive real-world usage, since we don't have that real-world validation that everything works as expected. Practically, there have not been code changes, so changing it locally to something lower would almost definitely work.

Thanks 😁
