### ISSUE TITLE
YGNodeClone memory leak

### ISSUE THREAD

**Issue by iCodeWoods** [facebook/yoga#1340]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce

YGNodeClone have memory leaks. Use Xcode->Instruments->Leaks can find it.

<img width="1668" alt="image" src="https://github.com/facebook/yoga/assets/30431268/3dad0e54-54dc-4840-9fc8-282ab0b48611">

<img width="741" alt="image" src="https://github.com/facebook/react-native/assets/30431268/68c5a015-15ed-436c-bb50-25be6a708996">

<img width="653" alt="image" src="https://github.com/facebook/react-native/assets/30431268/86da9c40-fabe-43d5-9997-bbee54ddc1fa">

<img width="1665" alt="image" src="https://github.com/facebook/react-native/assets/30431268/0f9c49db-a84e-4bb3-bb61-3f5e4925b0d3">

# Expected Behavior

Do not have memory leak.

# Actual Behavior

Do have memory leak.

# Link to Code

N/A

**Comment by NickGerleman** [comment]
Yoga calls `YGNodeClone` if the layout pass encounters a Yoga node which it needs to mutate, whose owner is different from the parent node we are laying out. It allows different Yoga trees to share nodes, and copy on write.

It is the callers responsibility to free the cloned node. E.g. with `YGNodeFreeRecursive`, or Yoga allows setting a callback for when a Node is cloned so that the host platform can handle this.

In this screenshot, it looks like this is happening in React Native's Paper renderer on iOS (guessing with nested views under text?). This is the code which is behaving incorrectly.

Please create an issue with a repro on the React Native repo for this. Because the React Native team is focused on shipping Fabric, we may not end up investigating Paper-specific changes, but PRs are always welcome.
