### ISSUE TITLE
Can run on Mac Catalyst, but cannot be archive on Mac Catalyst

### ISSUE THREAD

**Issue by jiasongs** [facebook/yoga#1443]
Problem: 
Archive on Mac Catalyst using Xcode 15.0, report some error
<img width="1210" alt="图片" src="https://github.com/facebook/yoga/assets/22904757/71d79c37-1fc2-4a6c-8f91-a1896ffde452">
<img width="265" alt="图片" src="https://github.com/facebook/yoga/assets/22904757/069f853a-c79c-4c45-b395-6788b00a4ac2">

Environment: 
Xcode 15.0, macOS 14.0

Demo: 
[Test.zip](https://github.com/facebook/yoga/files/13213838/Test.zip)

**Comment by NickGerleman** [comment]
I was able to repro. The generated [framework bundle](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPFrameworks/Concepts/FrameworkAnatomy.html) under Mac Catalyst specifically is missing the `PrivateHeaders` top-level symlink to `Versions/A/PrivateHeaders` (which does exist).

I think most of the manipulation/copying of headers is generated by CocoaPods/XCode, so I would suspect there might be a bug there with the combination of build settings being used here.

We also don't set an osx deployment target currently, but I don't know if that would effect this in any way.

Also adding @cipolleschi as resident CocoaPods/frameworks whisperer in case he knows.

**Comment by cipolleschi** [comment]
I saw something similar in the macOS repo. I am not sure how they works with private headers, but for MacOS the `React-RCTFabric` pod was creating the public headers in the `RCTFabric.framework/Versions/A/Headers/React` path instead of in the `RCTFabric.framework/Headers/React` path.

We fixed by setting [`PUBLIC_HEADERS_FOLDER_PATH`](https://developer.apple.com/documentation/xcode/build-settings-reference#Public-Headers-Folder-Path) to `RCTFabric.framework/Headers/React`.

Perhaps, you can try to play with [`PRIVATE_HEADERS_FOLDER_PATH`](https://developer.apple.com/documentation/xcode/build-settings-reference#Private-Headers-Folder-Path) and set it to `Yoga.framework/PrivateHeaders` and see whether it works! 

The settings that needs to be modified is the [`pod_target_xcconfig`](https://github.com/facebook/react-native/blob/main/packages/react-native/ReactCommon/yoga/Yoga.podspec#L33-L35)

**Comment by NickGerleman** [comment]
Should be fixed by https://github.com/facebook/yoga/commit/47a56db5f64c7230a64254c3d8e6f3bac3b4fb59

**Comment by jiasongs** [comment]
> 应由 [47a56db修复 ](https://github.com/facebook/yoga/commit/47a56db5f64c7230a64254c3d8e6f3bac3b4fb59)

<img width="448" alt="图片" src="https://github.com/facebook/yoga/assets/22904757/7f6576cd-4772-4636-b7fd-f788f3269b9e">
Thanks, `'HEADER_SEARCH_PATHS' => '$(PODS_TARGET_SRCROOT)'` works, but `ENV['USE_FRAMEWORKS'] != nil` is wrong, it is always nil.

**Comment by cipolleschi** [comment]
Hi @jiasongs, thanks for reporting.

When following our guidances, the env variable is not `nil` if you:
1. install the pods with the command `USE_FRAMEWORKS=static bundle exec pod install`
_or_
2. you call `use_frameworks!` before calling `use_react_native!` in your Podfile. We implemented a lookup [here](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L85).

If you are not following these guidelines, the env var might be `nil`, but we discourage that approach.

Can you share your Podfile, so we can inspect what's going wrong there?

**Comment by NickGerleman** [comment]
@cipolleschi this podspec is used outside of React Native, for users of standalone Yoga.

**Comment by cipolleschi** [comment]
oh... I see... so it is a different one! my bad, then... 🤔 
We might want to copy [this function](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L240-L256) in the Yoga podspec, then, and update it so that we can pass `self` as parameter (which should be the `target_definition`) to detect whether it is using frameworks or not....

@jiasongs do you have a reproducer I can play with to figure out which will be the best solution?

**Comment by NickGerleman** [comment]
> @jiasongs do you have a reproducer I can play with to figure out which will be the best solution?

There is a zip file in the issue description that I used for this earlier to repro.

**Comment by jiasongs** [comment]
> 哦...我明白了...所以这是一个不同的！ 我的错，那么...🤔 我们可能想在 Yoga podspec 中复制 [这个函数 ](https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/cocoapods/utils.rb#L240-L256)，然后更新它，以便我们可以通过 `self`作为参数（应该是 `target_definition`）来检测它是否正在使用框架......
> 
> @jiasongs你有一个复制器我可以用它来找出最好的解决方案吗？

Sorry for the late reply, there is a demo in this issue, link: https://github.com/facebook/yoga/files/13213838/Test.zip

**Comment by cipolleschi** [comment]
The commit should have landed earlier today.
