### ISSUE TITLE
Build of v3 with GCC11 fails

### ISSUE THREAD

**Issue by hedtke** [facebook/yoga#1590]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
Build with GCC11

# Expected Behavior
Successful Build

# Actual Behavior
warnings are treated as errors and there are conversion warnings

# Link to Code
https://c3i.jfrog.io/c3i/misc/logs/pr/23019/2-linux-gcc11/yoga/3.0.0//6557f18ca99c0b6a233f43db00e30efaa525e27e-build.txt

**Comment by NickGerleman** [comment]
Interesting… the continuous runs against GCC 11.4 (GCC from ubuntu-latest) seem to succeed. I can see 11.1 in the logs for the failing version. Maybe a difference in conversion warnings for constexpr numbers?

In general, I wonder if it would make sense for distribution on something like Conan to turn down some of the high warning level we opted into inside of the repo, so that users on compiler versions we don’t directly test won’t see new build errors. 

Otherwise, I suspect we could probably fix this by changing the width of some variables, but don’t have a nice way to test that locally.

**Comment by NickGerleman** [comment]
I’m going to remove GCC conversion warnings in OSS build.

**Comment by NickGerleman** [comment]
I will pick this as part of a new 3.x patch release.
