### ISSUE TITLE
Where is the operation interface?

### ISSUE THREAD

**Issue by fengcunwu** [facebook/yoga#1633]
# Report

- [ ] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
***Previous background operation interface***
![image](https://github.com/facebook/yoga/assets/48272463/8ec7f00e-e245-478c-85b2-29bf542f09bf)
***The current background operation interface***
<img width="1190" alt="image" src="https://github.com/facebook/yoga/assets/48272463/cda6f1d8-ee0b-4688-bdf7-3763923d3e00">

# Expected Behavior
***In the previous operation layout interface, the layout and hierarchical relationship of each element could be adjusted through configuration parameters. The current operation interface requires code changes, which feels very inconvenient!***

# Actual Behavior
***Describe what actually happened.***

# Link to Code
***If you have some code that maintainers can clone/test for themselves, bugs can be resolved much faster. Please paste a link here.***

***When applicable, use this [fiddle](https://jsfiddle.net/emilsjolander/jckmwztt/) to post a web repro.***

**Comment by dlh-Mr** [comment]
So what is the reason, please be specific, thank you @NickGerleman

**Comment by NickGerleman** [comment]
We needed to rewrite significant portion of playground when refreshing documentation platform.

I ended up choosing JSX, because it made the playground a lot quicker to work in for those with some existing experience in web (and because repoes we got were often running in Expo Snack, instead of trying to use Playground GUI).

A downside is that it is now less discoverable, especially for those who don’t work with React or React Native. I was a little surprised by how many folks used the Flexbox GUI.

I don’t think a GUI will come back, but improving discoverability has been on my mind, and is the action item for this.

**Comment by dlh-Mr** [comment]
Can I deploy Flexbox GUI myself? Could you please give me a relevant git address?

> 在刷新文档平台时，我们需要重写 Playground 的很大一部分。
> 
> 我最终选择了 JSX，因为它让那些拥有一些现有 Web 经验的人可以更快地在 Playground 上工作（而且因为我们得到的重现经常在 Expo Snack 中运行，而不是尝试使用 Playground GUI）。
> 
> 缺点是它现在不太容易被发现，特别是对于那些不使用 React 或 React Native 的人来说。我对有这么多人使用 Flexbox GUI 感到有点惊讶。
> 
> 我不认为 GUI 会回来，但提高可发现性一直是我的想法，也是为此采取的行动。

Can I deploy Flexbox GUI myself? Could you please give me a relevant git address? Or if I'm going to use the Flexbox GUI, what should I do?

**Comment by NickGerleman** [comment]
You could try hosting this: https://github.com/facebook/yoga/tree/release-v2.0/website

Note, that must either use `yarn --ignore-scripts` when installing, or run using Node 12, due to deprecated dependency.

**Comment by NickGerleman** [comment]
I changed things up so that an archive of the old website is visible at `https://old.yogalayout.dev`. Sometime in the future we will look at making current playground more discoverable for those who aren't used to JSX.
