### ISSUE TITLE
CocoaPods support

### ISSUE THREAD

**Issue by molon** [facebook/yoga#260]
I wrote a Objective-C wrapper named `MLLayout` depend on `css-layout`.
But following up on this library's update is inconvenient.
Can you consider adding CocoaPods support with the C implement?
:)

**Comment by guidomb** [comment]
What about also adding support for [Carthage](https://github.com/Carthage/Carthage)? It shouldn't be that much of a hazard to add an Xcode project that builds a `.framework`

**Comment by emilsjolander** [comment]
I'm very happy to support different package managers. @guidomb Could you submit a pull request with carthage support? I'm not very familiar with it but it looks cool.

**Comment by guidomb** [comment]
@emilsjolander Sure! I'll do it this weekend

**Comment by emilsjolander** [comment]
Thanks 👍

**Comment by guidomb** [comment]
I was about to work on this issue but I've realized that it was already been worked on https://github.com/facebook/yoga/pull/289

**Comment by dshahidehpour** [comment]
@guidomb We could still use CocoaPods support too :)

**Comment by guidomb** [comment]
@dshahidehpour Sure, more than happy to help. I'll until https://github.com/facebook/yoga/pull/289 gets merged and then I'll add CocoaPods support.

**Comment by hartbit** [comment]
@guidomb I started a pull request to support Carthage #305 but It might be easier to support both at the same time as the template for CocoaPods makes it support Carthage automatically. So you're welcome to take over if you want.

But I see several problems:

1) I hit a road-block supporting Carthage - which I think also exists with Cocoapods - because doing so breaks the buck build the project relies on to do continuous integration. I've described the problem in my PR #305.

2) I think both Carthage and Cocoapods make a huge deal about semver. But it seems that Yoga does not follow semver. Can you confirm this @dshahidehpour? What should we do about it?

**Comment by dshahidehpour** [comment]
I think we should start the talk about versioning YogaKit. Since we already have a lot of new changes coming (Swift, new syntax, etc.) I don't see why we shouldn't start having branches for this. 

@emilsjolander What do you think?

**Comment by emilsjolander** [comment]
@dshahidehpour semver is coming. i'm holding off on a couple big changes / fixes before marking a first version. Planning to do this very early january.

**Comment by guidomb** [comment]
@emilsjolander @dshahidehpour I've added support for CocoaPods in #309.

**Comment by dshahidehpour** [comment]
Added 7df6037
