### ISSUE TITLE
YGNodeChildCount unresolved external symbol with MSVC2015

### ISSUE THREAD

**Issue by roxlu** [facebook/yoga#281]
YGNodeChildCount is defined with inline. Shouldn't this be moved to Yoga.h? With the inline keyword it will result in a unresolved external symbol error on Windows MSVC2015.

**Comment by emilsjolander** [comment]
Good catch. Nothing the compilers I use complain about 😞 Feel free to submit a pull request with the change, otherwise I will try to get to it next week. Thanks for the heads up.

**Comment by splhack** [comment]
YGNodeGetChildCount is defined in Yoga.h and dllexport and inline should work as explained in this document.

https://msdn.microsoft.com/en-us/library/w8c3skw3.aspx

> You can define as inline a function with the dllexport attribute. In this case, the function is always instantiated and exported, whether or not any module in the program references the function. The function is presumed to be imported by another program.

**Comment by mafemergency** [comment]
This issue is closed, but was there a fix? I'm currently bumping into this
problem. Using VS2017 RC cl.exe version 19.10.24911

Building yoga as a shared library works as expected and exports all symbols I've
tried using, but building as a static library causes problems. Without link time
optimizations, `YGNodeGetChildCount` and `YGNodeStyleGetFlexBasis` can not be
used outside of `Yoga.c`. With lto in this instance, `YGNodeGetChildCount` works
but `YGNodeStyleGetFlexBasis` still doesn't.

Using `link /dump /symbols bin/yoga.lib` we can check that these functions are
absent, however other static functions that are defined and declared only in
`Yoga.c` are present like `YGFloatsEqual`. If we change `#define inline __inline`
to `#define inline __forceinline` we lose more (and gain one...):

```diff
-External | YGNodeStyleGetFlexGrow
-External | YGNodeStyleGetFlexShrink
-Static   | YGValueResolve
-Static   | YGResolveDimensions
-Static   | YGFloatsEqual
-Static   | YGNodeLeadingMargin
-Static   | YGNodeLeadingPaddingAndBorder
-Static   | YGNodeTrailingPaddingAndBorder
-Static   | YGNodeMarginForAxis
-Static   | YGNodePaddingAndBorderForAxis
-Static   | YGNodeIsFlex
-Static   | YGNodeIsLeadingPosDefined
-Static   | YGNodeIsTrailingPosDefined
-Static   | YGNodeBoundAxis
+Static   | YGNodeRelativePosition
```

The external ones are interesting, we need those as they are part of the API.
Locally I've just been removing problematic `inline`, a proper fix would likely
need to move some functions into the header.
