### ISSUE TITLE
YogaKit not getting recognised in xcode 8.2.1 in a framework project

### ISSUE THREAD

**Issue by AF-Kanishka** [facebook/yoga#367]
Hi,

I am creating a new issue as I don't have permission to reopen the issue which was closed by a mod. 

# Issues and Steps to Reproduce

I have copied all the resources ( not using cocoapods) and have added them as compile time dependency in the framework project build phase just like the demo. But the compiler is not able to recognise yoga when I try view.yoga anywhere in the project.

I am able to navigate to the yoga class through "Jump to definition" though

# Expected Behavior
No compilation errors

# Actual Behavior
Yoga is not getting recognised on the class UIView

# Link to Code
https://github.com/AF-Kanishka/yoga-test

**Comment by dshahidehpour** [comment]
Okay, so I cloned your project, there are a number of problems.

1. You need a Bridging Header since you are usinig swift, checkout `YogaKitSample-Bridging-Header.h` in the sample project. [this](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html) should help.

2. You need to make sure you have all the proper files added to your **Build Phases**. Checkout the difference between the compiled sources in your project, and the compiled sources in the sample project.

3. Even when I removed the yoga code from your project, it still wouldn't build. It must be in a bad state.

**Comment by AF-Kanishka** [comment]
Ok. I am leaving work now. Will check it out as soon as I get home. Thanks.

**Comment by AF-Kanishka** [comment]
Hi @dshahidehpour ,

So sorry for getting back late. 

1. The code is compiling when I comment out the yoga part (self.view.yoga) in both the view controllers. Can you please check again?

2. I tried adding the bridging header. The issue still persists. 

3. I have pushed the code with bridging header to the repo. Please tell me if I am missing something. 

Thanks

**Comment by dshahidehpour** [comment]
@AF-Kanishka Can you update your project with your latest attempt at fixing it?

**Comment by AF-Kanishka** [comment]
@dshahidehpour I have updated it. The changes includes 
1. Added the bridging header
2. Commented out the yoga code in view controller which was causing the compilation error. So, it should build fine now. 

I couldn't try anything else as I have hit a road block. I know I am missing something, but don't know what it is.

**Comment by AF-Kanishka** [comment]
Hi @dshahidehpour ,

Did you get a chance to look at it?

**Comment by dshahidehpour** [comment]
Sorry @AF-Kanishka I've been tied-up. I can take one more look at this today.

**Comment by dshahidehpour** [comment]
Okay, I've taken a look at this, turns out you can't add Bridging Headers to Frameworks. So, if you are building a Swift framework, you are out of luck (sorry!)

Here's the error message:

![](http://i.imgur.com/tjHkzgw.png)

More follow-up about it [here](http://stackoverflow.com/questions/24875745/xcode-6-beta-4-using-bridging-headers-with-framework-targets-is-unsupported).
