### ISSUE TITLE
Provide asm.js compiled assets in npm package

### ISSUE THREAD

**Issue by pseudo-su** [facebook/yoga#444]
I'd like to use yoga to handle svg positioning + generation from a browser similar to this

http://blog.scottlogic.com/2015/02/02/svg-layout-flexbox.html

I was expecting to be able to install the yoga-layout npm package and 
```js
require('yoga-layout/dist/Yoga.browser.js')
```

Providing the asm.js bundled library could also help to implement #419

**Comment by arcanis** [comment]
The asm.js build should already be distributed along with the npm package. You just have to use `require("yoga-layout")`, and your bundler will pick the right build (because of [this line](https://github.com/facebook/yoga/blob/master/javascript/package.json#L12)).

**Comment by jaladankisuresh** [comment]
I had built svg layout engine called [placard](https://github.com/jaladankisuresh/placard) which uses yoga-layout internally for generating dynamic svg layouts.  Yes, it is inspired by [scottlogic post](http://blog.scottlogic.com/2015/02/02/svg-layout-flexbox.html) from Colin Eberhard. 

I hope, it could be of some help to the node community

**Comment by arcanis** [comment]
I just checked and the asm.js build is in the latest release:

```
❯ [mael-mbp?] /tmp ❯ ll node_modules/yoga-layout/build/Release

total 952K
drwxr-xr-x 3 mael wheel  102 Apr 18 17:45 obj.target
-rw-r--r-- 1 mael wheel 391K Feb 24 16:12 nbind.js
-rwxr-xr-x 1 mael wheel 559K Apr 18 17:45 nbind.node
```

**Comment by emilsjolander** [comment]
Closing as it seems to be there. I'll also make a new release this Friday. Re-open if you still have issues after that 👍

**Comment by gevgeny** [comment]
Should it also work in a browser ? Webpack answers with an error: 
```
ERROR in ./~/yoga-layout/build/Release/nbind.js
Module not found: Error: Can't resolve 'fs' in '.../node_modules/yoga-layout/build/Release'
 @ ./~/yoga-layout/build/Release/nbind.js 1:1365-1378
 @ ./~/yoga-layout/sources/entry-browser.js
 @ ./src/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.tsx
```

**Comment by arcanis** [comment]
That's weird - the build shouldn't need the `fs` module. Maybe a debug `fopen` symbol or similar has been left unguarded?

**Comment by gevgeny** [comment]
Found such code `...var nodeFS=require("fs");var nodePath=require("path")...` in `node_modules/yoga-layout/build/Release/nbind.js`

**Comment by gevgeny** [comment]
@arcanis btw, Does it make sense to use yoga in a browser if a browser has native css flexbox support ? what are the prose if does ?

**Comment by emilsjolander** [comment]
Yeah its useful at times in the browser :) for example if building webgl experiences.

**Comment by gevgeny** [comment]
What about DOM based on yoga ?

**Comment by emilsjolander** [comment]
Possibly, i'm not the right person to know that though

**Comment by chrisregnier** [comment]
I've spent a week trying to get this library working in the browser with no luck :(

I've got the same issues that it `Can't resolve 'fs' `in nbind.js . But after manually taking out the node code it fails with `Uncaught TypeError: Cannot read property 'slice' of null`, because `var sourceRegex = /^function\s*\(([^)]*)\)\s*{\s*([^*]*?)[\s;]*(?:return\s*(.*?)[;\s]*)?}$/;` fails to parse the functions its used on. 

After looking into that, it seems webpack/babel added names to the anonymous functions cause they weren't in the source and the regex doesn't parse functions with names. After fixing that I'm stuck at this one :
`Uncaught ReferenceError: _a is not defined`   from 
`_a = _typeModule(_typeModule), _nbind.Type = _a.Type, _nbind.makeType = _a.makeType, _nbind.getComplexType = _a.getComplexType, _nbind.structureList = _a.structureList;`

I suspect a lot of the problems are due to babel mangling things, but I've been trying for hours to figure out how to load a script as is w/o running it through babel-loader, and I can't find what I need.

Has anyone gotten this to work using webpack and got a solution for the require('fs') issue to start with?
As well, are there any actually working examples/tests that you have to validate that this works in the browser as published? And works by using require('yoga-layout')?

**Comment by emilsjolander** [comment]
I'll have a look at this before making the 1.5 release this coming week.

**Comment by gevgeny** [comment]
I fixed the `require('fs')` issue. Just added 
```
node: {
		fs: "empty",
		module: "empty"
	},
```
to the webpack config and it works in my TypeScript + webpack env. Also i can instruct how to generate typescript typings for the yoga if necessary ;)

**Comment by gevgeny** [comment]
The lib works like a charm in a browser. Here is how I render layouted elements:

```jsx
render() {
  const {layout } = this.props;
  return (
    <div
      style={{
        position: 'absolute',
        top: 0,
        left: 0,
        width: layout.width,
        height: layout.height,
        transform: `translate3d(${layout.left}px, ${layout.top}px, 0px)`
      }}
    >

    </div>
   )
}
```

**Comment by gevgeny** [comment]
The only issue to me right now is very small javascript documentation ;(

**Comment by emilsjolander** [comment]
Awesome! Yeah docs are sorely lacking. We would be very greatfull if you helped us out on that front as you are using it :)

**Comment by gevgeny** [comment]
I will try to share some source with basic layouts later

**Comment by chrisregnier** [comment]
Bah! Moving back to the code in node_modules with your fs: 'empty' fixes things. Looks like all the other issues were symptoms of working on the code locally.

I now have it loading in the browser finally! Only a bunch of weird warnings about it parsing the .hh and .cc files still left to go.
Thanks for the help!

Also as another example of using this lib in the browser, I'm trying to use this to position svg elements within react, where each component starts with <g> and a transform for the position. So this lib is super useful for me. Thanks.

**Comment by psuedoSudo** [comment]
I think my original issue would have been resolved by the `fs: 'empty'` and `module: 'empty'`.

Because I was getting errors resolving .cc and .hh files I assumed that the default entry point of the module mustn't have been the browser version.

I did eventually get emscripten and llvm working on my machine and realised that I got the same error messages when I manually compiled yoga for the browser.

**Comment by chrisregnier** [comment]
I figured out the .hh/.cc errors were from a dynamic require expression that tried to parse all the files in the same dir (#535), so hopefully that should be cleaned up for the next release.

**Comment by arcanis** [comment]
Oh, I see. Are you using Webpack 2? I used this asmjs version with Webpack 3, but didn't notice the error before.

**Comment by chrisregnier** [comment]
I've been using webpack 1, so perhaps they've fixed things in the newest versions.

**Comment by vincentriemer** [comment]
@chrisregnier I came across similar issues to you regarding babel and adding `"ignore": [ "node_modules/yoga-layout" ]` to `.babelrc` resolved the issue for me.

**Comment by andrewrothman** [comment]
I'm trying to use the `yoga-layout` package in my app using TypeScript and Rollup. I deleted the `node_modules` folder, did a `node-gyp rebuild` in both the package's and my own directories, and `npm rebuild`, but I still get this same error in the Chrome JS console every time:

```
Uncaught Error: Could not locate the bindings file. Tried:
/Users/andrew/myProject/nbind.node
/Users/andrew/myProject/build/nbind.node
/Users/andrew/myProject/build/Debug/nbind.node
/Users/andrew/myProject/build/Release/nbind.node
/Users/andrew/myProject/out/Debug/nbind.node
/Users/andrew/myProject/Debug/nbind.node
/Users/andrew/myProject/out/Release/nbind.node
/Users/andrew/myProject/Release/nbind.node
/Users/andrew/myProject/build/default/nbind.node
/Users/andrew/myProject/compiled/6.5.0/darwin/x64/nbind.node
/Users/andrew/myProject/nbind.js
/Users/andrew/myProject/build/nbind.js
/Users/andrew/myProject/build/Debug/nbind.js
/Users/andrew/myProject/build/Release/nbind.js
/Users/andrew/myProject/out/Debug/nbind.js
/Users/andrew/myProject/Debug/nbind.js
/Users/andrew/myProject/out/Release/nbind.js
/Users/andrew/myProject/Release/nbind.js
/Users/andrew/myProject/build/default/nbind.js
/Users/andrew/myProject/compiled/6.5.0/darwin/x64/nbind.js
``` 

It seems to not be looking in the `yoga-layout` package folder for the bindings, and instead looking at my project's code. Any ideas regarding what's going on here?

**Comment by larsonjj** [comment]
Found that indeed the asmjs build is included with the npm package (`v1.6.0`), but it produces the following error when imported using node v8.5.0 and npm v5.4.0:

```
TypeError: {} is not a function. (In '{}("")', '{}' is an instance of Object)
```

I was able to solve the issue by compiling the asmjs script locally via `npm run build:browser` using emscripten `v1.37.21` and the latest xcode command line tools (`Apple LLVM version 9.0.0 (clang-900.0.37)`). It produced the following file: https://gist.github.com/larsonjj/577c943f3a1ab7337c42940addf31270

If you replace your `node_modules/yoga-layout/build/Release/nbind.js` file with the linked gist above, it should alleviate the issues with `fs` and `path` imports.

This leads me to believe that the next asmjs build included in the npm package needs to be produced using the latest emscripten version to fix the problem going forward.

**Comment by gordonwoodhull** [comment]
Yoga is useful for doing flexbox layout in SVG.

I ran into the `_a is not defined` error mentioned above and ended up just correcting the offending line. Everything worked after that. Have not tried a later emscripten yet.

**Comment by scottmas** [comment]
@NickGerleman Could we begin providing the asm.js exports again? It would be pretty easy to begin distributing the asm.js versions again right? I'm running react-native and a library I'm consuming uses yoga-layout. I know it's weird since obviously there are native bindings to yoga in the project, but the library I'm consuming knows nothing about them. If we just could have the asm.js bindings back, the library would be happy. And in a RN environment, the code should execute at near native speeds as well since the asm.js will ultimately get compiled to Hermes bytecode (see https://github.com/facebook/hermes/issues/429)

I could take a whack at adding this back if there's no opposition from the maintainers
