### ISSUE TITLE
How is the performance comparison between Yoga with other layouts in iOS? Autolayout, Texture, etc.

### ISSUE THREAD

**Issue by ajanuar** [facebook/yoga#621]
I am curious how good the performance of Yoga in comparison with other layouts, like Autolayout or Texture?

**Comment by lucdion** [comment]
Hi @ajanuar, I've created the [Layout Framework Benchmark](https://github.com/lucdion/LayoutFrameworkBenchmark). 

The benchmark test the following layout frameworks:
* Auto layout
* Manual layout
* [FlexLayout](https://github.com/lucdion/FlexLayout)  
* [LayoutKit](https://github.com/linkedin/LayoutKit)  
* [PinLayout](https://github.com/mirego/PinLayout)  
* UIStackViews  

Yoga's performance hasn't been tested directly, but check FlexLayout's performance, it reflects the Yoga's performance since [FlexLayout](https://github.com/lucdion/FlexLayout) is a Swift interface for Yoga. 

You'll see that the performance is amazing.

Texture's hasn't been benchmarked, anyone interested could add it to the benchmark.

**Comment by ajanuar** [comment]
Sure, I can help to benchmark using Texture. 

But basically, Flex is **much much** faster than AutoLayout & UIStackViews.

**Comment by crossle** [comment]
What's result Texture vs FlexLayout?

**Comment by lucdion** [comment]
@crossle no one has added the Texture framework to the benchmark yet.

**Comment by ajanuar** [comment]
Sorry, i was busy with works before. I already created the comparison in my local, will request PR to 
@lucdion soon. Do you test the performance in real devices?

**Comment by lucdion** [comment]
yes @ajanuar, benchmark must be executed on real devices. Test it on devices that you have. I could benchmark other devices later.
