### ISSUE TITLE
Documentation on how to use `setMeasureFunc` in JS

### ISSUE THREAD

**Issue by ahmedlhanafy** [facebook/yoga#778]
I'm trying to figure out how to use `setMeasureFunc` in JS but failed to find any examples, would be great if someone can help me with that.

**Comment by ahmedlhanafy** [comment]
@vincentriemer maybe you help with this one?

**Comment by vincentriemer** [comment]
I've since moved away from the included asmjs bindings of this repo to my own, but here's what my measure function looked like back when I was using the asmjs build: https://github.com/vincentriemer/react-native-dom/blob/146afe3fcdb5bbd9d9425e68bbf8e4e885299a44/ReactDom/views/Text/RCTShadowText.js#L140

**Comment by NickGerleman** [comment]
As of 1813748eaa60e6129c1e1c00c08322b5687b1702 we also export TypeScript types for this based on the previous Flow types. (Though this issue got me to go check more closely and notice we can make them better 🙂 https://github.com/facebook/yoga/pull/1198).
