### ISSUE TITLE
`npm install` always builds for the node platform regardless of settings.

### ISSUE THREAD

**Issue by seanparsons** [facebook/yoga#789]
# Report

- [x] I have searched [existing issues](https://github.com/facebook/yoga/issues) and this is not a duplicate

# Issues and Steps to Reproduce
`npm install` assumes the `node` platform.

# Expected Behavior
I'd expect the platform config as specified in the JavaScript section of the readme to apply and build for the browser if set as such.

# Actual Behavior
`npm install` invokes `npm run build:node` directly: https://github.com/facebook/yoga/blob/master/javascript/package.json#L30

**Comment by matthewww** [comment]
Also, there appears to be no `build:standalone` in the package.json.
As per the readme: https://github.com/facebook/yoga#build-platforms

**Comment by queequac** [comment]
Same here, cannot build for `browser `platform. :(

**Comment by queequac** [comment]
Unfortunately the official yoga project never answered to any of the browser-related questions and issues... I ended up using typeflex (https://github.com/dead/typeflex).
If you are interested in the browser as your target platform and you are using TS anyway, this might be a perfect match. And even if you are more into plain JS, just transpile it into the bundle you are looking for.

Only drawback: Since this port is the result of a one-man-show, this might lack any future enhancements. (But it passes all tests of yoga and yoga seems to be quite feature-complete anyway.)

**Comment by NickGerleman** [comment]
It looks like this has been updated since the issue was created.
