### ISSUE TITLE
yoga and Yoga

### ISSUE THREAD

**Issue by carlhuting** [facebook/yoga#802]
https://github.com/facebook/yoga/blob/master/Yoga.podspec
https://github.com/facebook/react-native/blob/master/ReactCommon/yoga/yoga.podspec

how to use them in one app?

**Comment by passy** [comment]
I'm not familiar with cocoapods so maybe that's a very obvious thing, but what's the problem you run into when using them and why would you want to use both in the same app?

**Comment by carlhuting** [comment]
There two teams, one use React Native 0.55.4 , the other use Yoga 0.1.9 。 Integrate into one App, conflicting.

frustrating

**Comment by EternalChildren** [comment]
i have the same problem,  i have to pod 'yoga' in Podfile when i enjoy react-native by integration with Existing Apps. so how to use the yoga version for react-native in Existing App. @passy

**Comment by passy** [comment]
Sorry, I'm not the right point of contact here. I don't know anything about Cocoapods or building iOS apps for that matter.

**Comment by koenpunt** [comment]
I have been trying this too, but since React Native ships with its own version of Yoga, the implementation conflicts. E.g. cocoapods installs files of the 2 into the same directory, removing the files of whichever is installed first. 
But I think this bug should probably be reported on the React Native repo; they could distribute their yoga under a different name (e.g. `ReactYoga`), which should resolve the naming issue.
Although then there still probably remains a duplicate symbol issue.

**Comment by NickGerleman** [comment]
Please feel free to create this as a new issue on the RN repository for avoiding the conflict.
