### ISSUE TITLE
Should the childWidth also 

### ISSUE THREAD

**Issue by ezeqc** [facebook/yoga#983]
I hit the error 

C rootcontextdata.cpp:ygLogger : availableWidth is indefinite so widthMeasureMode must be YGMeasureModeUndefined

Xcode debugger shows me the stack trace and on this line

https://github.com/facebook/yoga/blob/b280a19b0a61d6119ac48b441bcfd9cedd416113/yoga/Yoga.cpp#L2256

childMainSize = 1.00000002E+21
isMainAxisRow = true
childCrossSize = 540

The childHeight calculation uses `!isMainAxisRow`

https://github.com/facebook/yoga/blob/b280a19b0a61d6119ac48b441bcfd9cedd416113/yoga/Yoga.cpp#L2257

and i'm wondering if the childWidth should also use `!isMainAxisRow` like the childHeight calculation?

thanks for any feedback.

**Comment by ezeqc** [comment]
The eventual error happens because that childMainSize is passed down as availableWidth to YGNodelayoutImpl and then this check will fail 

```
static void YGNodelayoutImpl(
    const YGNodeRef node,
    const float availableWidth,
    const float availableHeight,
    const YGDirection ownerDirection,
    const YGMeasureMode widthMeasureMode,
    const YGMeasureMode heightMeasureMode,
    const float ownerWidth,
    const float ownerHeight,
    const bool performLayout,
    const YGConfigRef config) {
  YGAssertWithNode(
      node,
      YGFloatIsUndefined(availableWidth)
          ? widthMeasureMode == YGMeasureModeUndefined
          : true,
      "availableWidth is indefinite so widthMeasureMode must be "
      "YGMeasureModeUndefined");
```

**Comment by woehrl01** [comment]
Hi @ezeqc

Let me help to clarify things here. Having ! for width and not for height is correct. The reason is that if the main axis is row we can use that dimension as  width, if it's column we can use it as height. The reason is that for some values e. g. percentage calculations we need the dedicated width instead of the relative main dimensions for the algorithm.

Hope these makes things a little bit clearer. If not just raise your hands.

You mentioned you get an assertion error. In which specific case do you encounter that behavior?
